### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by arenmarsden** [Dragory/Knub#14]
Hi, 

I'm wanting to use Knub in a Discord bot I'm working for my server, we intend for the bot to eventually become open source under the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.en.html), however I'm noticing some conflicts on the repository vs the Node Repositories.

The GitHub repository has no explicit license, inferring that is is all rights reserved and we need to discuss a private license, however, the Node Package Manager says the project is licensed under MIT, in which case all I would need to do is state that the project uses libraries which are licensed under MIT (or relicense my project)

Please let me know what's going on and if we need to discuss something privately.

**Comment by axisiscool** [comment]
According to Dragory, Knub is licensed under [MIT](https://spdx.org/licenses/MIT.html).

![Discord_gtzQg9ke9l](https://user-images.githubusercontent.com/54381371/139508107-aadbbb9a-d6d3-4699-9d4a-a1ed3f1d210f.png)
